export const mediaPath = (product, kind, file) => `/api/media/${product}/${kind}/${file}`;

const clip = (product, file, poster, objectPosition = 'center center') => ({
  src: mediaPath(product, 'video', file),
  poster: mediaPath(product, 'images', poster),
  objectPosition,
});

export const priceCards = [
  {
    brand: 'SERGIO TACCHINI',
    model: 'CUSHLITE 302',
    price: '₩159,000',
    role: 'DAILY BALANCE',
    summary: '자연스러운 보행과 가벼운 코트를 잇는 루틴형 설계',
    image: mediaPath('302', 'images', 'cushlite-302-all-colors.jpg'),
    accent: 'moss',
  },
  {
    brand: 'SERGIO TACCHINI',
    model: 'CUSHLITE 702',
    price: '₩179,000',
    role: 'COURT BALANCE',
    summary: '반복 착지와 방향 전환의 균형을 일상까지 잇는 설계',
    image: mediaPath('702', 'images', 'price/court-linea-colors.webp'),
    accent: 'ice',
  },
];

export const competitors = [
  {
    brand: 'ON',
    brandKey: 'on',
    tier: 'daily',
    priceValue: 169000,
    model: 'THE ROGER Clubhouse',
    price: '₩169,000',
    role: 'DAILY · TENNIS LIFESTYLE',
    feature: '클래식 테니스 실루엣과 온종일 편안함을 앞세운 일상 중심 모델',
    image: 'https://images.ctfassets.net/hnk2vsx53n6l/30HVZIOqEBsajvshHWQaie/1bd563554cb8002b9841ee670fb9ad9b/4cdeb44e355c7cd4b72745bffc44cd9de0719ba3.png?fm=webp',
    technologies: ['Lifestyle court style', 'All-day comfort'],
    emphasis: ['daily'],
    emphasisLabels: { daily: 'CloudTec® 쿠션' },
    ratings: { daily: 95, multi: 45, speed: 35, cushion: 70, support: 45, durability: 55 },
    source: 'https://www.on.com/ko-kr/products/the-roger-clubhouse-3mf1054',
  },
  {
    brand: 'ON',
    brandKey: 'on',
    tier: 'crossover',
    priceValue: 209000,
    model: 'THE ROGER Clubhouse Pro',
    price: '₩209,000',
    role: 'MULTI-COURT · ON/OFF COURT',
    feature: '라켓 스포츠 성능과 일상 착화의 연속성을 직접 겨냥한 프리미엄 모델',
    image: 'https://images.ctfassets.net/hnk2vsx53n6l/3Kw2lFTFCkPTnHTgpEpKgs/979c2e4daa8711c3abdb7545ceddc188/a24ae2027e5575510651965f1d10df85ea97ef86.png?fm=webp',
    technologies: ['3/4 Speedboard®', 'Helion™ · CloudTec®'],
    emphasis: ['daily', 'multi', 'cushion', 'support', 'durability'],
    emphasisLabels: {
      daily: 'Helion™ 폼',
      multi: '헤링본 아웃솔',
      cushion: 'CloudTec®',
      support: '3/4 Speedboard®',
      durability: 'TPU 토 캡',
    },
    ratings: { daily: 80, multi: 85, speed: 65, cushion: 82, support: 78, durability: 76 },
    source: 'https://www.on.com/ko-kr/products/the-roger-clubhouse-pro-m-3md3003',
  },
  {
    brand: 'ON',
    brandKey: 'on',
    tier: 'performance',
    priceValue: 259000,
    model: 'THE ROGER Pro 3',
    price: '₩259,000',
    role: 'HARD COURT · PERFORMANCE',
    feature: '빠른 움직임과 정교한 제동을 위해 반발력과 케이지 지지를 강화한 경기형 모델',
    image: 'https://images.ctfassets.net/hnk2vsx53n6l/6OATjM50bbZbf9o0a16yQd/1e6c8f68f1e84f02947ae4722fbe0a99/c46d7d2a7675bc45e6122cf7b3f83a8be124bd58.png?fm=webp',
    technologies: ['Helion™ HF', 'Carbon Speedboard®'],
    emphasis: ['speed', 'cushion', 'support', 'durability'],
    emphasisLabels: {
      speed: 'Carbon Speedboard®',
      cushion: 'Helion™ HF',
      support: '미드풋 케이지',
      durability: '러버 아웃솔',
    },
    ratings: { daily: 30, multi: 80, speed: 95, cushion: 88, support: 92, durability: 90 },
    source: 'https://www.on.com/ko-kr/products/the-roger-pro-3-m-3mg1036',
  },
  {
    brand: 'ASICS',
    brandKey: 'asics',
    tier: 'speed',
    priceValue: 159000,
    model: 'SOLUTION SPEED FF 3',
    price: '₩159,000',
    role: 'ALL COURT · SPEED',
    feature: '가볍고 빠른 전진과 민첩한 코트 커버를 우선한 스피드형 모델',
    image: 'https://images.asics.com/is/image/asics/1041A438_800_SL_LT_GLB?$sfcc-product$=',
    technologies: ['SPEEDTRUSS™', 'Engineered outsole'],
    emphasis: ['multi', 'speed'],
    emphasisLabels: { multi: 'PRECISION-SOLE™', speed: 'SPEEDTRUSS™' },
    ratings: { daily: 20, multi: 85, speed: 95, cushion: 62, support: 60, durability: 68 },
    source: 'https://asics.co.kr/p/AKR_112512035-701',
  },
  {
    brand: 'ASICS',
    brandKey: 'asics',
    tier: 'stability',
    priceValue: 179000,
    model: 'GEL-RESOLUTION X',
    price: '₩179,000',
    role: 'BASELINE · LATERAL STABILITY',
    feature: '베이스라인 좌우 커버와 급격한 방향 전환에서의 홀드에 집중한 안정형 설계',
    image: mediaPath('302', 'images', 'competitors/asics-gel-resolution-x.jpg'),
    technologies: ['DYNAWALL™', 'PGUARD™ · AHARPLUS™'],
    emphasis: ['multi', 'cushion', 'support', 'durability'],
    emphasisLabels: {
      multi: 'DYNAWALL™',
      cushion: 'Forefoot GEL™',
      support: 'DYNALACING™',
      durability: 'PGUARD™',
    },
    ratings: { daily: 20, multi: 90, speed: 60, cushion: 84, support: 95, durability: 92 },
    source: 'https://m.asics.co.kr/p/AKR_112612011-402',
  },
  {
    brand: 'ASICS',
    brandKey: 'asics',
    tier: 'performance',
    priceValue: 199000,
    model: 'COURT FF 3',
    price: '₩199,000',
    role: 'ALL COURT · POWER & RECOVERY',
    feature: '강한 스윙 뒤 빠른 복귀와 회전 동작을 위해 중족부 제어를 강화한 상위 경기형 모델',
    image: 'https://images.asics.com/is/image/asics/1041A370_103_SL_LT_GLB?$sfcc-product$=',
    technologies: ['TWISTRUSS™', 'FLYTEFOAM™ · GEL™'],
    emphasis: ['multi', 'speed', 'cushion', 'support', 'durability'],
    emphasisLabels: {
      multi: 'TWISTRUSS™',
      speed: 'TWISTRUSS™',
      cushion: 'FLYTEFOAM™ · GEL™',
      support: '와이드 아웃솔',
      durability: 'AHARPLUS™',
    },
    ratings: { daily: 15, multi: 92, speed: 82, cushion: 88, support: 90, durability: 90 },
    source: 'https://www.asics.co.kr/p/21189',
  },
  {
    brand: 'ADIDAS',
    brandKey: 'adidas',
    tier: 'speed',
    priceValue: 149000,
    model: 'Defiant Speed 2',
    price: '₩149,000',
    role: 'HARD COURT · SPEED ENTRY',
    feature: '빠른 코트 움직임을 보다 낮은 가격대에서 제안하는 스피드 엔트리 모델',
    image: 'https://assets.adidas.com/images/w_500,f_auto,q_auto/f6875367348b4e26baf18180a7824998_9366/2_White_JR1746_01_00_standard.jpg',
    technologies: ['Speed-focused fit', 'Hard-court setup'],
    emphasis: ['speed'],
    emphasisLabels: { speed: 'Lightstrike' },
    ratings: { daily: 20, multi: 78, speed: 90, cushion: 62, support: 58, durability: 65 },
    source: 'https://www.adidas.co.kr/%EB%94%94%ED%8C%8C%EC%9D%B4%EC%96%B8%ED%8A%B8-%EC%8A%A4%ED%94%BC%EB%93%9C-2-%ED%85%8C%EB%8B%88%EC%8A%A4%ED%99%94/JR1746.html',
  },
  {
    brand: 'ADIDAS',
    brandKey: 'adidas',
    tier: 'speed',
    priceValue: 169000,
    model: 'Adizero Ubersonic 5',
    price: '₩169,000',
    role: 'HARD COURT · LIGHTWEIGHT SPEED',
    feature: '낮고 빠른 움직임과 경량 반응성을 중심으로 구성한 아디제로 코트 모델',
    image: 'https://assets.adidas.com/images/w_500,f_auto,q_auto/965f45a4a24a480f94eac28088e5f186_9366/5_White_KK3844_01_00_standard.jpg',
    technologies: ['Lightstrike cushioning', 'Adizero construction'],
    emphasis: ['speed', 'multi', 'cushion'],
    emphasisLabels: { speed: 'Speedframe', multi: '하프 부티 구조', cushion: 'Lightstrike' },
    ratings: { daily: 15, multi: 86, speed: 94, cushion: 70, support: 68, durability: 68 },
    source: 'https://www.adidas.co.kr/%EC%95%84%EB%94%94%EC%A0%9C%EB%A1%9C-%EC%9A%B0%EB%B2%84%EC%86%8C%EB%8B%89-5/KK3844.html',
  },
  {
    brand: 'ADIDAS',
    brandKey: 'adidas',
    tier: 'stability',
    priceValue: 179000,
    model: 'Barricade 14',
    price: '₩179,000',
    role: 'HARD COURT · CONTROL',
    feature: '전족부 추진과 뒤꿈치 충격 흡수, 중족부 제어를 구역별로 나눈 경기형 설계',
    image: mediaPath('302', 'images', 'competitors/adidas-barricade-14.jpg'),
    technologies: ['LIGHTSTRIKE PRO', 'REPETITOR · LIGHTTRAXION'],
    emphasis: ['multi', 'cushion', 'support', 'durability'],
    emphasisLabels: {
      multi: 'Lighttraxion',
      cushion: 'REPETITOR',
      support: 'Chassis + Claw',
      durability: 'Adituff',
    },
    ratings: { daily: 15, multi: 92, speed: 68, cushion: 85, support: 95, durability: 94 },
    source: 'https://www.adidas.co.kr/%EB%B0%94%EB%A6%AC%EC%BC%80%EC%9D%B4%EB%93%9C-14-%ED%85%8C%EB%8B%88%EC%8A%A4%ED%99%94/JS2561.html',
  },
];

export const routinePairs = [
  {
    time: '07:30',
    leftCode: 'WALK',
    rightCode: 'ACTIVE',
    leftTitle: '아침의 가벼운 워킹',
    rightTitle: '코트 위의 액티브 리듬감',
    left: clip('302', 'routine-walking.mp4', 'routine-walking-poster.jpg'),
    right: clip('702', '702-tennis.mp4', '702-tennis-poster.jpg'),
    leftLabel: '몸의 리듬을 깨우는 첫 움직임',
    rightLabel: '집중과 방향 전환을 여는 첫 스텝',
  },
  {
    time: '13:10',
    leftCode: 'RESET',
    rightCode: 'RECOVER',
    leftTitle: '일상 속 밸런스 리셋',
    rightTitle: '웰니스한 밸런스 휴식',
    left: clip('302', 'routine-cafe.mp4', 'routine-cafe-poster.jpg'),
    right: clip('702', '702-cafe.mp4', '702-cafe-poster.jpg'),
    leftLabel: '움직임 사이 호흡을 고르는 시간',
    rightLabel: '코트 뒤 몸과 마음의 균형을 회복',
  },
  {
    time: '18:30',
    leftCode: 'COURT',
    rightCode: 'EASE',
    leftTitle: '코트로 향하는 순간',
    rightTitle: '일상에서의 편안한 여유',
    left: clip('302', 'routine-court.mp4', 'routine-court-poster.jpg'),
    right: clip('702', '702-resort.mp4', '702-resort-poster.jpg'),
    leftLabel: '일상의 걸음을 코트의 움직임으로',
    rightLabel: '코트의 균형을 휴식까지 이어가는 순간',
  },
];

const point = (code, label, detail, anchor, labelPosition, align = 'left') => ({
  code,
  label,
  detail,
  anchor,
  labelPosition,
  align,
});

export const heroScene = {
  id: 'hero',
  holdAfterFirstPlay: true,
  kicker: 'SERGIO TACCHINI · CUSHLITE LINEUP',
  title: '일상의 웰니스,\n코트의 밸런스.',
  left: {
    model: 'CUSHLITE 302',
    role: 'DAILY BALANCE',
    title: '일상에서 코트로.',
    body: '매일 같은 시간의 움직임을 가볍게 시작하는 루틴형 설계.',
    clips: [clip('302', 'intro.mp4', 'intro-poster.webp', 'center bottom')],
  },
  right: {
    model: 'CUSHLITE 702',
    role: 'COURT BALANCE',
    title: '코트에서 일상으로.',
    body: '반복 착지와 방향 전환의 균형을 매일의 리듬까지 이어가는 설계.',
    clips: [clip('702', 'hero-turn.mp4', 'hero-poster.jpg', 'center center')],
  },
};

export const dualScenes = [
  {
    id: 'fit-upper',
    index: '01',
    title: '착화의 시작과 움직임을 감싸는 방식.',
    left: {
      model: 'CUSHLITE 302',
      eyebrow: 'EASY ENTRY',
      title: '신는 순간부터, 하루의 리듬을 가볍게.',
      body: '길게 올라온 힐탭과 부드러운 카라가 매일 반복하는 첫 착화 동작을 간결하게 안내합니다.',
      specs: ['Extended heel pull', 'Soft entry collar', 'Low-friction lining'],
      clips: [clip('302', 'easy-entry-full.mp4', 'easy-entry-full-poster.jpg', 'center bottom')],
      annotations: [
        point('EN-01', 'EXTENDED HEEL PULL', 'One-hand entry support', [25, 54], [7, 31]),
        point('EN-02', 'PADDED ENTRY', 'Soft collar contact', [39, 60], [92, 29], 'right'),
      ],
    },
    right: {
      model: 'CUSHLITE 702',
      eyebrow: 'LATERAL UPPER',
      title: '유연하게 반응하고, 중심은 흐트러지지 않도록.',
      body: '패딩 카라가 뒤꿈치를 부드럽게 감싼 뒤, 측면 메시와 필름 오버레이가 움직임을 따라 중족부를 지지합니다.',
      specs: ['Padded collar', 'Lateral mesh', 'No-sew film overlay'],
      clips: [clip('702', 'heel-ankle.mp4', 'heel-ankle-poster.jpg', 'center center')],
      annotations: [
        point('UP-01', 'LATERAL MESH', 'Breathable sidewall textile', [32, 53], [7, 26]),
        point('UP-02', 'LACE SUPPORT', 'Midfoot hold system', [45, 41], [92, 24], 'right'),
      ],
    },
  },
  {
    id: 'heel-stability',
    index: '02',
    independentPanelScrub: true,
    title: '안정을 지지해주는 서로 다른 기능.',
    left: {
      model: 'CUSHLITE 302',
      eyebrow: 'EXTERNAL HEEL SUPPORT',
      title: '바깥에서 감싸고, 미드솔까지 연결하도록.',
      body: '유광 TPU 클립이 힐 카운터 바깥을 감싸며 착지와 방향 전환의 좌우 움직임을 지지합니다.',
      specs: ['Gloss TPU clip', 'Lateral containment', 'Midsole anchor'],
      clips: [clip('302', 'heel-tpu.mp4', 'heel-tpu-poster.webp', 'center center')],
      annotations: [
        point('HL-01', 'GLOSS TPU CLIP', 'External rearfoot frame', [58, 49], [92, 27], 'right'),
        point('HL-02', 'MIDSOLE ANCHOR', 'Frame-to-foam connection', [57, 67], [7, 76]),
      ],
    },
    right: {
      model: 'CUSHLITE 702',
      eyebrow: 'INJECTED ARCH SUPPORT',
      title: '아치 아래를, 사출 구조로 지지.',
      body: '뒤꿈치 지지 프레임과 아치 아래 사출 브리지, 분할 러버가 미드솔을 중심으로 연결됩니다. 아치 하부를 받치며 반복 착지에서 중족부 비틀림을 줄입니다.',
      specs: ['Rearfoot frame', 'Injected arch support', 'Split rubber base'],
      clips: [clip('702', 'arch-exploded.mp4', 'arch-exploded-poster.jpg', 'center center')],
      annotations: [
        point('ST-01', 'REARFOOT FRAME', 'External heel support path', [62, 39], [92, 20], 'right'),
        point('ST-02', 'INJECTED ARCH BRIDGE', 'Under-arch torsion support', [48, 62], [7, 79]),
      ],
    },
  },
  {
    id: 'cushion-balance',
    index: '03',
    title: '쿠셔닝과 안정감 사이, 각자의 균형.',
    left: {
      model: 'CUSHLITE 302',
      eyebrow: 'UPPER TO MIDSOLE BALANCE',
      title: '유연한 움직임 위에, 필요한 지지를.',
      body: '메시 어퍼와 넓은 미드솔 플랫폼이 일상 보행과 가벼운 코트 움직임을 하나의 설계로 연결합니다.',
      specs: ['Flexible mesh', 'No-sew frame', 'Wide platform'],
      clips: [{
        ...clip('302', '302-move-2.mp4', '302-move-2-poster.jpg', 'center center'),
      }],
      annotations: [
        point('CU-01', 'FLEX MESH', 'Adaptive movement layer', [37, 43], [7, 25]),
        point('CU-02', 'WIDE PLATFORM', 'Stable landing footprint', [49, 73], [92, 78], 'right'),
      ],
    },
    right: {
      model: 'CUSHLITE 702',
      eyebrow: 'BALANCED CUSHIONING',
      title: '반복 착지에도, 중심의 균형을 유지하도록.',
      body: '뒤꿈치의 충격을 받아들이는 쿠셔닝과 넓은 플랫폼을 조율해 좌우 하중 이동을 안정적으로 받칩니다.',
      specs: ['Controlled cushion', 'Stable platform', 'Balanced rebound'],
      clips: [{
        ...clip('702', 'landing-jump.mp4', 'landing-jump-poster.jpg', 'center bottom'),
        startTime: 2,
      }],
      annotations: [
        point('BL-01', 'CONTROLLED CUSHION', 'Soft impact, measured rebound', [45, 73], [7, 79]),
        point('BL-02', 'STABLE PLATFORM', 'Reduced lateral collapse', [59, 79], [92, 80], 'right'),
      ],
    },
  },
  {
    id: 'motion-control',
    index: '04',
    title: '자연스러운 전진과 단단한 중심 제어.',
    loopWhileActive: true,
    left: {
      model: 'CUSHLITE 302',
      eyebrow: 'NATURAL FOREFOOT',
      title: '낮은 전족부로, 코트의 안정감을.',
      body: '낮은 전족부 곡률이 접지 구간을 길게 가져가 일상 보행에서 코트의 다음 스텝까지 이어줍니다.',
      specs: ['Low toe spring', 'Long forefoot contact', 'Natural flex point'],
      clips: [{
        ...clip('302', 'toe-spring.mp4', 'toe-spring-poster.webp', '46% center'),
        framed: true,
      }],
      annotations: [
        point('TF-01', 'LOW TOE SPRING', 'Natural forefoot angle', [41, 74], [7, 81]),
        point('TF-02', 'CONTACT LINE', 'Extended ground feel', [56, 79], [92, 81], 'right'),
      ],
    },
    right: {
      model: 'CUSHLITE 702',
      eyebrow: 'FOREFOOT TRANSITION',
      title: '딛는 순간부터, 다음 방향으로 밀어내도록.',
      body: '전족부의 접지 구간과 굴곡 라인이 하중 이동을 받아 발끝의 롤링과 푸시오프를 코트의 다음 스텝으로 이어줍니다.',
      specs: ['Forefoot flex zone', 'Directional push-off', 'Ground contact'],
      clips: [clip('702', 'lifestyle-forefoot.mp4', 'lifestyle-forefoot-poster.jpg', 'center bottom')],
      annotations: [
        point('FF-01', 'FOREFOOT CONTACT', 'Extended ground transition', [56, 76], [7, 73]),
        point('FF-02', 'PUSH-OFF ZONE', 'Directional toe release', [69, 79], [92, 75], 'right'),
      ],
    },
  },
  {
    id: 'outsole-transition',
    index: '05',
    title: '걷고, 밀고, 방향을 바꾸는 바닥의 설계.',
    holdAfterFirstPlay: true,
    sync: {
      sharedCue: 0.79,
      leftCue: 0.571,
      rightCue: 0.789,
    },
    left: {
      model: 'CUSHLITE 302',
      eyebrow: 'HERINGBONE OUTSOLE',
      title: '일상의 접지에서, 가벼운 코트 전환까지.',
      body: '촘촘한 헤링본 러그와 중앙 회전 영역을 연결해 보행과 코트의 접점을 구분했습니다.',
      specs: ['Herringbone grip', 'Midfoot cutaway', 'Pivot circle'],
      clips: [clip('302', 'outsole.mp4', 'outsole-poster.jpg', 'center center')],
      annotations: [
        point('OU-01', 'HERRINGBONE GRIP', 'Daily-to-court traction', [61, 47], [92, 24], 'right'),
        point('OU-02', 'PIVOT CIRCLE', 'Rotation release zone', [64, 65], [92, 77], 'right'),
      ],
    },
    right: {
      model: 'CUSHLITE 702',
      eyebrow: 'RUBBER OUTSOLE',
      title: '멈추고, 밀고, 자신의 리듬으로 전환하도록.',
      body: '파동형 러그와 중앙 홈이 하드코트의 접지와 회전 동작을 한쪽으로 치우치지 않게 연결합니다.',
      specs: ['Wave traction', 'Pivot zone', 'Heel brake'],
      clips: [clip('702', 'rubber-turn.mp4', 'rubber-poster.jpg', 'center center')],
      annotations: [
        point('RB-01', 'WAVE TRACTION', 'Multi-direction lug map', [39, 54], [92, 28], 'right'),
        point('RB-02', 'HEEL BRAKE', 'Deceleration contact zone', [53, 57], [92, 79], 'right'),
      ],
    },
  },
];

export const colorScene = {
  left: {
    model: 'CUSHLITE 302',
    eyebrow: 'FOUR DAILY TONES',
    title: '차분한 컬러 팔레트로, 매일의 루틴에 네 가지 선택.',
    image: mediaPath('302', 'images', 'color-variations.jpg'),
  },
  right: {
    model: 'CUSHLITE 702',
    eyebrow: 'FOUR COURT MOODS',
    title: '절제된 구조에, 서로 다른 네 가지 무드.',
    image: mediaPath('702', 'images', 'price/court-linea-colors.webp'),
  },
};

export const closingScene = {
  left: {
    model: 'CUSHLITE 302',
    label: '매일 가볍게 시작하는 루틴',
    clips: [clip('302', 'closing-footwork.mp4', 'closing-poster.webp', 'center center')],
  },
  right: {
    model: 'CUSHLITE 702',
    label: '자신의 리듬을 지키는 코트 루틴',
    clips: [clip('702', 'lifestyle-forefoot.mp4', 'lifestyle-forefoot-poster.jpg', 'center center')],
  },
};
