const PRODUCT = '702';

export const assetPath = (path) => {
  const normalizedPath = path.replace(/^\/+/, '');

  // 영상·제품 이미지는 저장소에 두지 않고 S3 에 올린 뒤 서버가 중계한다.
  // (페이지 저장으로 자산이 함께 내려가지 않도록, 또 public 저장소에
  //  미출시 제품 자산이 남지 않도록)
  // 미디어 경로는 앱 서버 루트 기준이라 BASE_URL 을 붙이지 않는다.
  const media = normalizedPath.match(/(?:^|\/)(video|images)\/(.+)$/);
  if (media) return `/api/media/${PRODUCT}/${media[1]}/${media[2]}`;

  return `${import.meta.env.BASE_URL}${normalizedPath}`;
};

export const priceBenchmarks = [
  {
    brand: 'SERGIO TACCHINI',
    model: 'CUSHLITE 702',
    price: '₩189,000',
    priceDelta: '비교 기준',
    segment: '쿠션·안정 균형형',
    functions: ['듀얼 존 CMEVA', '중족부 브리지', '온코트 ↔ 데일리 연속성'],
    verdict: '상단 가격대에서 특정 기능의 극대화보다 매일 반복 가능한 균형을 제안합니다.',
    featured: true,
    image: assetPath('assets/images/price/court-linea-colors.webp'),
    imageAlt: '화이트, 아이스 블루, 라임, 핑크 컬러의 CUSHLITE 702 테니스화',
  },
  {
    brand: 'NIKE',
    model: 'Vapor Pro 2',
    price: '₩159,000',
    priceDelta: '− ₩30,000',
    segment: '스피드·민첩형',
    functions: ['낮은 코트 필링', '경량 어퍼', '빠른 전환 반응'],
    verdict: '비교군 최저 가격. 쿠셔닝의 양보다 코트 감각과 민첩한 움직임에 우선순위를 둡니다.',
    image: assetPath('assets/images/price/nike-vapor-pro-2.webp'),
    imageAlt: '화이트 컬러 Nike Vapor Pro 2 테니스화',
  },
  {
    brand: 'ADIDAS',
    model: 'Barricade 13',
    price: '₩179,000',
    priceDelta: '− ₩10,000',
    segment: '지지·내구형',
    functions: ['측면 지지 구조', '내구성 중심 어퍼', '안정적인 베이스'],
    verdict: '강한 방향 전환과 반복 슬라이드에서 흔들림을 줄이는 안정성 중심의 선택입니다.',
    image: assetPath('assets/images/price/adidas-barricade-13.webp'),
    imageAlt: '화이트 컬러 adidas Barricade 13 테니스화',
  },
  {
    brand: 'ASICS',
    model: 'Gel Resolution 9',
    price: '₩189,000',
    priceDelta: '동일 가격',
    segment: '안정·쿠션 강화형',
    functions: ['후족부 충격 완화', '측면 안정 구조', '넓은 지지 플랫폼'],
    verdict: '동일 가격대에서 안정성과 충격 완화의 체감 강도를 더 선명하게 가져가는 포지션입니다.',
    image: assetPath('assets/images/price/asics-gel-resolution-9.webp'),
    imageAlt: '화이트와 블루 컬러 ASICS GEL-RESOLUTION 9 테니스화',
  },
];

export const features = [
  {
    id: 'upper',
    name: 'Lateral upper',
    korean: '측면은 가볍게, 움직임은 단단하게.',
    body:
      '측면의 오픈 메쉬는 열을 빠르게 흘려보내고 발의 움직임에 맞춰 유연하게 반응합니다. 힘이 모이는 중족부에는 무봉제 필름 오버레이와 레이스 케이지를 겹쳐, 방향 전환에서도 형태가 흐트러지지 않도록 지지합니다.',
    specs: ['Lateral open-knit mesh', 'No-sew film overlay', 'Midfoot lace support'],
    mediaType: 'video',
    media: assetPath('assets/video/upper-side.mp4'),
    poster: assetPath('assets/images/upper-side-poster.jpg'),
    fallback: assetPath('assets/images/upper-side-poster.jpg'),
    mediaAlt: '테니스화의 측면 메쉬와 필름 오버레이를 보여주는 영상',
    tone: 'ice',
    scrollVideo: {
      holdStart: 0.44,
      holdFrame: 1,
      holdEnd: 0.58,
      endFrame: 1,
    },
    annotations: [
      {
        code: 'UP-01',
        label: 'LATERAL MESH',
        detail: 'Breathable sidewall textile',
        anchor: [29, 51],
        elbow: [25, 28],
        labelPosition: [8, 28],
        align: 'left',
        mobile: { anchor: [36, 52], elbow: [30, 28], labelPosition: [7, 28] },
      },
      {
        code: 'UP-02',
        label: 'LACE SUPPORT',
        detail: 'Midfoot hold system',
        anchor: [38, 39],
        elbow: [70, 18],
        labelPosition: [92, 18],
        align: 'right',
        mobile: { anchor: [47, 39], elbow: [67, 18], labelPosition: [93, 18] },
      },
      {
        code: 'UP-03',
        label: 'FILM OVERLAY',
        detail: 'No-sew lateral reinforcement',
        anchor: [36, 48],
        elbow: [76, 79],
        labelPosition: [93, 79],
        align: 'right',
        mobile: { anchor: [44, 49], elbow: [72, 62], labelPosition: [93, 62] },
      },
    ],
  },
  {
    id: 'heel',
    name: 'Heel structure',
    korean: '뒤꿈치가 흔들리지 않도록.',
    body:
      '넓게 감싸는 힐 카운터와 바깥으로 확장된 베이스를 조합했습니다. 발이 신발 안에서 뜨는 느낌을 줄이고, 오픈 스탠스 착지에서 안정적인 기준점을 만드는 설계입니다.',
    specs: ['Sculpted heel counter', 'Wide landing base', 'Padded collar'],
    mediaType: 'video',
    media: assetPath('assets/video/heel-ankle.mp4'),
    poster: assetPath('assets/images/heel-ankle-poster.jpg'),
    fallback: assetPath('assets/images/heel-ankle-poster.jpg'),
    mediaAlt: '착화 상태에서 뒤꿈치와 힐 카운터를 보여주는 테니스화 영상',
    tone: 'steel',
    annotations: [
      {
        code: 'HL-01',
        label: 'PADDED COLLAR',
        detail: 'Achilles comfort zone',
        anchor: [53, 31],
        elbow: [71, 18],
        labelPosition: [92, 18],
        align: 'right',
        mobile: { anchor: [53, 31], elbow: [69, 17], labelPosition: [93, 17] },
      },
      {
        code: 'HL-02',
        label: 'SCULPTED COUNTER',
        detail: 'Rearfoot containment shell',
        anchor: [57, 48],
        elbow: [76, 45],
        labelPosition: [93, 45],
        align: 'right',
        mobile: { anchor: [57, 48], elbow: [73, 45], labelPosition: [93, 45] },
      },
      {
        code: 'HL-03',
        label: 'LANDING FLARE',
        detail: 'Extended lateral base',
        anchor: [58, 70],
        elbow: [75, 77],
        labelPosition: [93, 77],
        align: 'right',
        mobile: { anchor: [59, 69], elbow: [72, 78], labelPosition: [93, 78] },
      },
    ],
  },
  {
    id: 'arch',
    name: 'Midfoot chassis',
    korean: '분리된 구조가, 중심을 지지하다.',
    body:
      '아웃솔과 미드솔 사이에 배치한 중족부 브리지는 발의 가운데를 단단히 잡고, 앞뒤 구획이 각자의 움직임을 이어가도록 연결합니다. 착지 뒤에는 불필요한 비틀림을 줄이고, 다음 스텝에서는 자연스러운 굴곡을 남기는 구조입니다.',
    specs: ['Midfoot support bridge', 'Split flex geometry', 'Torsion control chassis'],
    mediaType: 'video',
    media: assetPath('assets/video/arch-exploded.mp4'),
    poster: assetPath('assets/images/arch-exploded-poster.jpg'),
    fallback: assetPath('assets/images/arch-exploded-poster.jpg'),
    mediaAlt: '중족부 브리지와 아웃솔 구조를 분리해 보여주는 테니스화 영상',
    tone: 'deep',
    annotations: [
      {
        code: 'AR-01',
        label: 'MIDFOOT BRIDGE',
        detail: 'Torsion control chassis',
        anchor: [49, 56],
        elbow: [26, 65],
        labelPosition: [7, 65],
        align: 'left',
        mobile: { anchor: [49, 56], elbow: [30, 66], labelPosition: [7, 66] },
      },
      {
        code: 'AR-02',
        label: 'SPLIT FLEX BASE',
        detail: 'Independent forefoot flex',
        anchor: [35, 68],
        elbow: [76, 71],
        labelPosition: [93, 71],
        align: 'right',
        mobile: { anchor: [35, 68], elbow: [76, 71], labelPosition: [93, 71] },
      },
      {
        code: 'AR-03',
        label: 'HEEL PLATFORM',
        detail: 'Stabilized rearfoot base',
        anchor: [67, 68],
        elbow: [76, 84],
        labelPosition: [93, 84],
        align: 'right',
        mobile: { anchor: [67, 68], elbow: [76, 84], labelPosition: [93, 84] },
      },
    ],
  },
  {
    id: 'rubber',
    name: 'Rubber outsole',
    korean: '멈추고, 밀고, 다시 방향을 바꾸는 패턴.',
    body:
      '파동형 러그를 전족과 뒤꿈치에 나누고 중앙 홈으로 회전 동작을 연결했습니다. 하드코트를 기준으로 접지와 슬라이드가 한쪽으로 치우치지 않도록 설계한 러버 구성입니다.',
    specs: ['Wave traction map', 'Shore A 64 target', 'Hard-court compound'],
    mediaType: 'video',
    media: assetPath('assets/video/rubber-turn.mp4'),
    poster: assetPath('assets/images/rubber-poster.jpg'),
    fallback: assetPath('assets/images/IMG_5231-stage.webp'),
    mediaAlt: '테니스 풋워크에서 아웃솔 구조로 이어지는 테니스화 영상',
    tone: 'light',
    scrollVideo: {
      holdStart: 1,
      holdFrame: 1,
      endFrame: 1,
    },
    annotations: [
      {
        code: 'RB-01',
        label: 'WAVE TRACTION',
        detail: 'Multi-direction lug map',
        anchor: [38, 53],
        elbow: [72, 28],
        labelPosition: [93, 28],
        align: 'right',
        mobile: { anchor: [38, 53], elbow: [69, 27], labelPosition: [93, 27] },
      },
      {
        code: 'RB-02',
        label: 'PIVOT ZONE',
        detail: 'Rotation release point',
        anchor: [67, 60],
        elbow: [79, 52],
        labelPosition: [93, 52],
        align: 'right',
        mobile: { anchor: [65, 60], elbow: [78, 52], labelPosition: [93, 52] },
      },
      {
        code: 'RB-03',
        label: 'HEEL BRAKE',
        detail: 'Deceleration contact zone',
        anchor: [52, 56],
        elbow: [72, 78],
        labelPosition: [93, 78],
        align: 'right',
        mobile: { anchor: [51, 57], elbow: [70, 79], labelPosition: [93, 79] },
      },
    ],
  },
  {
    id: 'midsole',
    name: 'Balanced cushioning',
    korean: '쿠셔닝과 안정감 사이, 정확한 균형.',
    body:
      '무조건 푹신한 감각을 목표로 하지 않았습니다. 뒤꿈치 충격은 부드럽게 분산하면서, 좌우 하중 이동에서는 미드솔이 과도하게 무너지지 않도록 밀도를 조율했습니다. 반복 착지와 방향 전환을 함께 고려한 밸런스입니다.',
    specs: ['Balanced CMEVA density', 'Controlled compression', 'Stable heel platform'],
    mediaType: 'video',
    media: assetPath('assets/video/balance-on-foot.mp4'),
    poster: assetPath('assets/images/balance-poster.jpg'),
    fallback: assetPath('assets/images/balance-poster.jpg'),
    mediaAlt: '체중 이동에 따라 쿠셔닝과 안정감을 보여주는 테니스화 착화 영상',
    tone: 'mist',
    scrollVideo: {
      holdStart: 1,
      holdFrame: 1,
      endFrame: 1,
      revealEnd: 'top 22%',
      navigationAnchor: 0.25,
    },
    annotations: [
      {
        code: 'BL-01',
        label: 'CONTROLLED CUSHION',
        detail: 'Soft impact, measured rebound',
        anchor: [44, 73],
        elbow: [24, 81],
        labelPosition: [7, 81],
        align: 'left',
        mobile: { anchor: [47, 73], elbow: [26, 81], labelPosition: [7, 81] },
      },
      {
        code: 'BL-02',
        label: 'STABLE PLATFORM',
        detail: 'Reduced lateral collapse',
        anchor: [58, 78],
        elbow: [79, 82],
        labelPosition: [93, 82],
        align: 'right',
        mobile: { anchor: [56, 78], elbow: [79, 82], labelPosition: [93, 82] },
      },
      {
        code: 'BL-03',
        label: 'BALANCED REBOUND',
        detail: 'Smooth weight transition',
        anchor: [68, 65],
        elbow: [29, 51],
        labelPosition: [7, 51],
        align: 'left',
        mobile: { anchor: [66, 66], elbow: [29, 51], labelPosition: [7, 51] },
      },
    ],
  },
  {
    id: 'cushioning',
    name: 'Cushioning in motion',
    korean: '착지 순간을 부드럽게 받아내다.',
    body:
      '정지된 단면이 아니라 실제 체중 이동에서 쿠셔닝을 확인합니다. 넓은 힐 CMEVA가 첫 충격을 분산하고, 곡면 미드솔이 다음 스텝으로 이어지는 구름 동작을 돕습니다.',
    specs: ['Heel impact dispersion', 'CMEVA compression zone', 'Wide landing platform'],
    mediaType: 'video',
    media: assetPath('assets/video/cushioning-on-foot.mp4'),
    poster: assetPath('assets/images/cushioning-poster.jpg'),
    fallback: assetPath('assets/images/IMG_5228-stage.webp'),
    mediaAlt: '착지하며 뒤꿈치 쿠셔닝을 보여주는 테니스화 착화 영상',
    tone: 'mist',
    scrollVideo: {
      holdStart: 1,
      holdFrame: 1,
      endFrame: 1,
      revealEnd: 'top 22%',
      navigationAnchor: 0.25,
    },
    annotations: [
      {
        code: 'CS-01',
        label: 'HEEL CMEVA',
        detail: 'Vertical impact absorption',
        anchor: [43, 82],
        elbow: [28, 72],
        labelPosition: [7, 72],
        align: 'left',
        mobile: { anchor: [55, 80], elbow: [28, 72], labelPosition: [7, 72] },
      },
      {
        code: 'CS-02',
        label: 'WIDE HEEL BASE',
        detail: 'Stable landing platform',
        anchor: [49, 91],
        elbow: [80, 84],
        labelPosition: [93, 84],
        align: 'right',
        mobile: { anchor: [50, 90], elbow: [80, 84], labelPosition: [93, 84] },
      },
      {
        code: 'CS-03',
        label: 'COLLAR HOLD',
        detail: 'Stable heel containment',
        anchor: [38, 43],
        elbow: [78, 31],
        labelPosition: [93, 31],
        align: 'right',
        mobile: { anchor: [45, 45], elbow: [80, 48], labelPosition: [93, 48] },
      },
    ],
  },
  {
    id: 'lifestyle',
    name: 'Court to everyday',
    korean: '테니스와 웰니스 라이프의 경계를 허물다.',
    body:
      '코트화의 안정감은 유지하면서 일상 착장에서도 편안하게 보이도록 전족부 볼륨과 토 스프링을 다듬었습니다. 발가락이 자연스럽게 펼쳐지고, 보행 시 부드럽게 굴러가는 설계입니다.',
    specs: ['Relaxed forefoot volume', 'Natural toe splay', 'Court-to-street comfort'],
    mediaType: 'video',
    media: assetPath('assets/video/lifestyle-forefoot.mp4'),
    poster: assetPath('assets/images/lifestyle-forefoot-poster.jpg'),
    fallback: assetPath('assets/images/IMG_5230-stage.webp'),
    mediaAlt: '테니스화를 일상복과 함께 착용하고 걷는 모습',
    tone: 'mist',
    scrollVideo: {
      holdStart: 0.44,
      holdFrame: 0.74,
      holdEnd: 0.62,
      endFrame: 0.96,
    },
    annotations: [
      {
        code: 'LF-01',
        label: 'RELAXED TOE BOX',
        detail: 'Everyday forefoot room',
        anchor: [68, 77],
        elbow: [86, 66],
        labelPosition: [94, 66],
        align: 'right',
        mobile: { anchor: [62, 78], elbow: [80, 77], labelPosition: [93, 77] },
      },
      {
        code: 'LF-02',
        label: 'TOE SPRING',
        detail: 'Smooth walking transition',
        anchor: [72, 86],
        elbow: [88, 88],
        labelPosition: [94, 88],
        align: 'right',
        mobile: { anchor: [64, 84], elbow: [80, 88], labelPosition: [93, 88] },
      },
      {
        code: 'LF-03',
        label: 'FLEX ZONE',
        detail: 'Natural forefoot roll',
        anchor: [60, 84],
        elbow: [55, 88],
        labelPosition: [41, 88],
        align: 'left',
        mobile: { anchor: [52, 84], elbow: [38, 88], labelPosition: [7, 88] },
      },
    ],
  },
];

export const colorways = [
  {
    name: 'Chalk White',
    bg: '#e9e9e6',
  },
  {
    name: 'Ice Blue',
    bg: '#b9d5e8',
  },
  {
    name: 'Soft Lime',
    bg: '#d8d99c',
  },
  {
    name: 'Court Pink',
    bg: '#e8bcc7',
  },
];
