const PRODUCT = '702';

export const assetPath = (path) => {
  const normalizedPath = path.replace(/^\/+/, '');

  // 영상·제품 이미지는 저장소에 두지 않고 S3 에 올린 뒤 서버가 중계한다.
  // 미디어 경로는 앱 서버 루트 기준이라 BASE_URL 을 붙이지 않는다.
  const media = normalizedPath.match(/(?:^|\/)(video|images)\/(.+)$/);
  if (media) return `/api/media/${PRODUCT}/${media[1]}/${media[2]}`;

  return `${import.meta.env.BASE_URL}${normalizedPath}`;
};

export const priceBenchmarks = [
  {
    brand: 'SERGIO TACCHINI',
    model: 'CUSHLITE 702',
    price: '₩179,000',
    priceDelta: 'BALANCED ROUTINE',
    segment: '쿠션·안정 균형형',
    functions: ['듀얼 존 CMEVA', '중족부 브리지', '온코트 ↔ 데일리 연속성'],
    verdict: '측면 지지, 착지 완충과 전환 안정의 균형으로 매일 자신의 루틴을 지키는 설계입니다.',
    featured: true,
    image: assetPath('assets/images/price/court-linea-colors.webp'),
    imageAlt: '화이트, 아이스 블루, 라임, 핑크 컬러의 CUSHLITE 702 테니스화',
  },
  {
    brand: 'NIKE',
    model: 'Vapor Pro 2',
    price: '₩159,000',
    priceDelta: 'SPEED RESPONSE',
    segment: '스피드·민첩형',
    functions: ['낮은 코트 필링', '경량 어퍼', '빠른 전환 반응'],
    verdict: '낮은 코트 감각과 민첩한 전환에 우선순위를 둔 스피드 성향입니다.',
    image: assetPath('assets/images/price/nike-vapor-pro-2.webp'),
    imageAlt: '화이트 컬러 Nike Vapor Pro 2 테니스화',
  },
  {
    brand: 'ADIDAS',
    model: 'Barricade 13',
    price: '₩179,000',
    priceDelta: 'STABILITY',
    segment: '지지·내구형',
    functions: ['측면 지지 구조', '내구성 중심 어퍼', '안정적인 베이스'],
    verdict: '강한 방향 전환과 반복 슬라이드에서 흔들림을 줄이는 안정성 중심의 선택입니다.',
    image: assetPath('assets/images/price/adidas-barricade-13.webp'),
    imageAlt: '화이트 컬러 adidas Barricade 13 테니스화',
  },
  {
    brand: 'ASICS',
    model: 'Gel Resolution 9',
    price: '₩189,000',
    priceDelta: 'BASELINE SUPPORT',
    segment: '안정·쿠션 강화형',
    functions: ['후족부 충격 완화', '측면 안정 구조', '넓은 지지 플랫폼'],
    verdict: '베이스라인 좌우 이동의 지지와 착지 완충을 우선하는 포지션입니다.',
    image: assetPath('assets/images/price/asics-gel-resolution-9.webp'),
    imageAlt: '화이트와 블루 컬러 ASICS GEL-RESOLUTION 9 테니스화',
  },
];

export const features = [
  {
    id: 'upper',
    name: 'Lateral upper',
    korean: '유연하게 반응하고, 중심은 흐트러지지 않도록.',
    body:
      '측면의 오픈 메쉬가 발의 움직임을 따라 유연하게 반응하고, 힘이 모이는 중족부에는 무봉제 필름 오버레이와 레이스 지지 구조를 겹쳤습니다. 반복되는 방향 전환에서도 중심을 지키도록 구성했습니다.',
    specs: ['Lateral open-knit mesh', 'No-sew film overlay', 'Midfoot lace support'],
    mediaType: 'video',
    media: assetPath('assets/video/upper-side.mp4'),
    poster: assetPath('assets/images/upper-side-poster.jpg'),
    fallback: assetPath('assets/images/upper-side-poster.jpg'),
    mediaAlt: '테니스화의 측면 메쉬와 필름 오버레이를 보여주는 영상',
    tone: 'ice',
    scrollVideo: {
      holdStart: 0.44,
      holdFrame: 1,
      holdEnd: 0.58,
      endFrame: 1,
    },
    annotations: [
      {
        code: 'UP-01',
        label: 'LATERAL MESH',
        detail: 'Breathable sidewall textile',
        anchor: [29, 51],
        elbow: [25, 28],
        labelPosition: [8, 28],
        align: 'left',
        mobile: { anchor: [36, 52], elbow: [30, 28], labelPosition: [7, 28] },
      },
      {
        code: 'UP-02',
        label: 'LACE SUPPORT',
        detail: 'Midfoot hold system',
        anchor: [38, 39],
        elbow: [70, 18],
        labelPosition: [92, 18],
        align: 'right',
        mobile: { anchor: [47, 39], elbow: [67, 18], labelPosition: [93, 18] },
      },
      {
        code: 'UP-03',
        label: 'FILM OVERLAY',
        detail: 'No-sew lateral reinforcement',
        anchor: [36, 48],
        elbow: [76, 79],
        labelPosition: [93, 79],
        align: 'right',
        mobile: { anchor: [44, 49], elbow: [72, 62], labelPosition: [93, 62] },
      },
    ],
  },
  {
    id: 'heel',
    name: 'Heel structure',
    korean: '뒤꿈치의 기준을 단단하게.',
    body:
      '넓게 감싸는 힐 카운터와 바깥으로 확장된 베이스를 조합했습니다. 반복되는 오픈 스탠스 착지에서 뒤꿈치를 지지하고, 자신의 움직임을 이어가는 기준점을 만듭니다.',
    specs: ['Sculpted heel counter', 'Wide landing base', 'Padded collar'],
    mediaType: 'video',
    media: assetPath('assets/video/heel-ankle.mp4'),
    poster: assetPath('assets/images/heel-ankle-poster.jpg'),
    fallback: assetPath('assets/images/heel-ankle-poster.jpg'),
    mediaAlt: '착화 상태에서 뒤꿈치와 힐 카운터를 보여주는 테니스화 영상',
    tone: 'steel',
    annotations: [
      {
        code: 'HL-01',
        label: 'PADDED COLLAR',
        detail: 'Achilles comfort zone',
        anchor: [53, 31],
        elbow: [71, 18],
        labelPosition: [92, 18],
        align: 'right',
        mobile: { anchor: [53, 31], elbow: [69, 17], labelPosition: [93, 17] },
      },
      {
        code: 'HL-02',
        label: 'SCULPTED COUNTER',
        detail: 'Rearfoot containment shell',
        anchor: [57, 48],
        elbow: [76, 45],
        labelPosition: [93, 45],
        align: 'right',
        mobile: { anchor: [57, 48], elbow: [73, 45], labelPosition: [93, 45] },
      },
      {
        code: 'HL-03',
        label: 'LANDING FLARE',
        detail: 'Extended lateral base',
        anchor: [58, 70],
        elbow: [75, 77],
        labelPosition: [93, 77],
        align: 'right',
        mobile: { anchor: [59, 69], elbow: [72, 78], labelPosition: [93, 78] },
      },
    ],
  },
  {
    id: 'arch',
    name: 'Arch support bridge',
    korean: '움직임은 나누고, 중심의 균형은 이어가도록.',
    body:
      '아웃솔과 미드솔 사이, 아치 아래에 배치한 사출형 브리지가 앞뒤 구획을 연결합니다. 아치 하부를 받치며 착지 때 중족부 비틀림을 줄이고, 다음 스텝에서는 전족부 굴곡이 자연스럽게 이어지도록 구성했습니다.',
    specs: ['Injected arch support', 'Split flex geometry', 'Torsion guidance'],
    mediaType: 'video',
    media: assetPath('assets/video/arch-exploded.mp4'),
    poster: assetPath('assets/images/arch-exploded-poster.jpg'),
    fallback: assetPath('assets/images/arch-exploded-poster.jpg'),
    mediaAlt: '아치 아래 사출 브리지와 아웃솔 구조를 분리해 보여주는 테니스화 영상',
    tone: 'deep',
    annotations: [
      {
        code: 'AR-01',
        label: 'INJECTED ARCH BRIDGE',
        detail: 'Under-arch torsion support',
        anchor: [49, 56],
        elbow: [26, 65],
        labelPosition: [7, 65],
        align: 'left',
        mobile: { anchor: [49, 56], elbow: [30, 66], labelPosition: [7, 66] },
      },
      {
        code: 'AR-02',
        label: 'SPLIT FLEX BASE',
        detail: 'Independent forefoot flex',
        anchor: [35, 68],
        elbow: [76, 71],
        labelPosition: [93, 71],
        align: 'right',
        mobile: { anchor: [35, 68], elbow: [76, 71], labelPosition: [93, 71] },
      },
      {
        code: 'AR-03',
        label: 'HEEL PLATFORM',
        detail: 'Stabilized rearfoot base',
        anchor: [67, 68],
        elbow: [76, 84],
        labelPosition: [93, 84],
        align: 'right',
        mobile: { anchor: [67, 68], elbow: [76, 84], labelPosition: [93, 84] },
      },
    ],
  },
  {
    id: 'rubber',
    name: 'Rubber outsole',
    korean: '멈추고, 밀고, 자신의 리듬으로 전환하도록.',
    body:
      '파동형 러그를 전족과 뒤꿈치에 나누고 중앙 홈으로 회전 동작을 연결했습니다. 하드코트를 기준으로 접지와 슬라이드가 한쪽으로 치우치지 않도록 설계한 러버 구성입니다.',
    specs: ['Wave traction map', 'Shore A 64 target', 'Hard-court compound'],
    mediaType: 'video',
    media: assetPath('assets/video/rubber-turn.mp4'),
    poster: assetPath('assets/images/rubber-poster.jpg'),
    fallback: assetPath('assets/images/IMG_5231-stage.webp'),
    mediaAlt: '테니스 풋워크에서 아웃솔 구조로 이어지는 테니스화 영상',
    tone: 'light',
    scrollVideo: {
      holdStart: 1,
      holdFrame: 1,
      endFrame: 1,
    },
    annotations: [
      {
        code: 'RB-01',
        label: 'WAVE TRACTION',
        detail: 'Multi-direction lug map',
        anchor: [38, 53],
        elbow: [72, 28],
        labelPosition: [93, 28],
        align: 'right',
        mobile: { anchor: [38, 53], elbow: [69, 27], labelPosition: [93, 27] },
      },
      {
        code: 'RB-02',
        label: 'PIVOT ZONE',
        detail: 'Rotation release point',
        anchor: [67, 60],
        elbow: [79, 52],
        labelPosition: [93, 52],
        align: 'right',
        mobile: { anchor: [65, 60], elbow: [78, 52], labelPosition: [93, 52] },
      },
      {
        code: 'RB-03',
        label: 'HEEL BRAKE',
        detail: 'Deceleration contact zone',
        anchor: [52, 56],
        elbow: [72, 78],
        labelPosition: [93, 78],
        align: 'right',
        mobile: { anchor: [51, 57], elbow: [70, 79], labelPosition: [93, 79] },
      },
    ],
  },
  {
    id: 'midsole',
    name: 'Balanced cushioning',
    korean: '쿠셔닝과 안정감 사이, 조율된 균형.',
    body:
      '뒤꿈치 구간은 착지 충격을 받아들이고, 넓은 플랫폼은 좌우 하중 이동에서 형태를 유지하도록 구성했습니다. 과도한 쿠셔닝보다 반복 착지와 방향 전환에 필요한 균형을 우선한 미드솔 설계입니다.',
    specs: ['Balanced CMEVA density', 'Controlled compression', 'Stable heel platform'],
    mediaType: 'video',
    media: assetPath('assets/video/balance-on-foot.mp4'),
    poster: assetPath('assets/images/balance-poster.jpg'),
    fallback: assetPath('assets/images/balance-poster.jpg'),
    mediaAlt: '체중 이동에 따라 쿠셔닝과 안정감을 보여주는 테니스화 착화 영상',
    tone: 'mist',
    scrollVideo: {
      holdStart: 1,
      holdFrame: 1,
      endFrame: 1,
      revealEnd: 'top 22%',
      navigationAnchor: 0.25,
    },
    annotations: [
      {
        code: 'BL-01',
        label: 'CONTROLLED CUSHION',
        detail: 'Soft impact, measured rebound',
        anchor: [44, 73],
        elbow: [24, 81],
        labelPosition: [7, 81],
        align: 'left',
        mobile: { anchor: [47, 73], elbow: [26, 81], labelPosition: [7, 81] },
      },
      {
        code: 'BL-02',
        label: 'STABLE PLATFORM',
        detail: 'Reduced lateral collapse',
        anchor: [58, 78],
        elbow: [79, 82],
        labelPosition: [93, 82],
        align: 'right',
        mobile: { anchor: [56, 78], elbow: [79, 82], labelPosition: [93, 82] },
      },
      {
        code: 'BL-03',
        label: 'BALANCED REBOUND',
        detail: 'Smooth weight transition',
        anchor: [68, 65],
        elbow: [29, 51],
        labelPosition: [7, 51],
        align: 'left',
        mobile: { anchor: [66, 66], elbow: [29, 51], labelPosition: [7, 51] },
      },
    ],
  },
  {
    id: 'cushioning',
    name: 'Cushioning in motion',
    korean: '착지의 충격은 받아내고, 다음 움직임은 이어가도록.',
    body:
      '실제 체중 이동에서 뒤꿈치 쿠셔닝이 눌리는 과정을 보여줍니다. 넓은 힐 구간에서 시작된 착지가 곡면 미드솔을 따라 다음 스텝으로 이어집니다.',
    specs: ['Heel impact dispersion', 'CMEVA compression zone', 'Wide landing platform'],
    mediaType: 'video',
    media: assetPath('assets/video/cushioning-on-foot.mp4'),
    poster: assetPath('assets/images/cushioning-poster.jpg'),
    fallback: assetPath('assets/images/IMG_5228-stage.webp'),
    mediaAlt: '착지하며 뒤꿈치 쿠셔닝을 보여주는 테니스화 착화 영상',
    tone: 'mist',
    scrollVideo: {
      holdStart: 1,
      holdFrame: 1,
      endFrame: 1,
      revealEnd: 'top 22%',
      navigationAnchor: 0.25,
    },
    annotations: [
      {
        code: 'CS-01',
        label: 'HEEL CMEVA',
        detail: 'Vertical impact absorption',
        anchor: [43, 82],
        elbow: [28, 72],
        labelPosition: [7, 72],
        align: 'left',
        mobile: { anchor: [55, 80], elbow: [28, 72], labelPosition: [7, 72] },
      },
      {
        code: 'CS-02',
        label: 'WIDE HEEL BASE',
        detail: 'Stable landing platform',
        anchor: [49, 91],
        elbow: [80, 84],
        labelPosition: [93, 84],
        align: 'right',
        mobile: { anchor: [50, 90], elbow: [80, 84], labelPosition: [93, 84] },
      },
      {
        code: 'CS-03',
        label: 'COLLAR HOLD',
        detail: 'Stable heel containment',
        anchor: [38, 43],
        elbow: [78, 31],
        labelPosition: [93, 31],
        align: 'right',
        mobile: { anchor: [45, 45], elbow: [80, 48], labelPosition: [93, 48] },
      },
    ],
  },
  {
    id: 'lifestyle',
    name: 'Court to routine',
    korean: '코트에서 지킨 균형을, 매일의 루틴까지.',
    body:
      '코트에서 필요한 안정적인 구조를 유지하면서 전족부 볼륨과 전체 실루엣을 자연스럽게 다듬었습니다. 운동하는 순간부터 운동 뒤의 일상까지, 몸을 관리하는 루틴이 흐트러지지 않도록 구성했습니다.',
    specs: ['Relaxed forefoot volume', 'Balanced walking transition', 'Court-to-routine comfort'],
    mediaType: 'video',
    media: assetPath('assets/video/lifestyle-forefoot.mp4'),
    poster: assetPath('assets/images/lifestyle-forefoot-poster.jpg'),
    fallback: assetPath('assets/images/IMG_5230-stage.webp'),
    mediaAlt: '테니스화를 일상복과 함께 착용하고 걷는 모습',
    tone: 'mist',
    scrollVideo: {
      holdStart: 0.44,
      holdFrame: 0.74,
      holdEnd: 0.62,
      endFrame: 0.96,
    },
    annotations: [
      {
        code: 'LF-01',
        label: 'RELAXED TOE BOX',
        detail: 'Everyday forefoot room',
        anchor: [68, 77],
        elbow: [86, 66],
        labelPosition: [94, 66],
        align: 'right',
        mobile: { anchor: [62, 78], elbow: [80, 77], labelPosition: [93, 77] },
      },
      {
        code: 'LF-02',
        label: 'TOE SPRING',
        detail: 'Smooth walking transition',
        anchor: [72, 86],
        elbow: [88, 88],
        labelPosition: [94, 88],
        align: 'right',
        mobile: { anchor: [64, 84], elbow: [80, 88], labelPosition: [93, 88] },
      },
      {
        code: 'LF-03',
        label: 'FLEX ZONE',
        detail: 'Natural forefoot roll',
        anchor: [60, 84],
        elbow: [55, 88],
        labelPosition: [41, 88],
        align: 'left',
        mobile: { anchor: [52, 84], elbow: [38, 88], labelPosition: [7, 88] },
      },
    ],
  },
];

export const colorways = [
  {
    name: 'Chalk White',
    bg: '#e9e9e6',
  },
  {
    name: 'Ice Blue',
    bg: '#b9d5e8',
  },
  {
    name: 'Soft Lime',
    bg: '#d8d99c',
  },
  {
    name: 'Court Pink',
    bg: '#e8bcc7',
  },
];
